services:
  api:
    command: pnpm --filter @braille-docs/api dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"

  web:
    command: pnpm --filter @braille-docs/web dev --host 0.0.0.0 --port 4321
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4321:4321"

  admin:
    command: pnpm --filter @braille-docs/admin dev --host 0.0.0.0 --port 5173
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  traefik:
    ports:
      - "8081:8080"
